const QUOTES = [
    "“La mediocrità non riconosce nulla che le sia superiore; ma il talento riconosce istantaneamente il genio.”\nSir Arthur Conan Doyle",
    "“Non piangere perché è finito, sorridi perché è successo.”\nGabriel García Márquez",
    "“Nessuna persona merita le tue lacrime, e chi le merita sicuramente non ti farà piangere.”\nGabriel García Márquez",
    "“Un vero amico è chi ti prende per la mano e ti tocca il cuore... sempre.”\nGabriel García Márquez",
    "“Il fatto che una persona non ti ami come tu vorresti non vuol dire che non ti ami con tutta se stessa.”\nGabriel García Márquez",
    "“E' la vita, più che la morte, a non avere limiti.”\nGabriel García Márquez",
    "“Ci sarà sempre chi ti critica, l'unica cosa da fare è continuare ad avere fiducia, stando attento a chi darai fiducia due volte.”\nGabriel García Márquez",
    "“Gli esseri umani non nascono sempre il giorno in cui le loro madri li danno alla luce, ma la vita li costringe ancora molte volte a partorirsi da sé.”\nGabriel García Márquez",
    "“Non c’è medicina che guarisca quello che non guarisce la felicità.”\nGabriel García Márquez",
    "“Le donne pensano più al senso recondito delle domande che alle domande stesse.”\nGabriel García Márquez",
    "“Nulla di quanto si fa a letto è immorale se contribuisce a perpetuare l’amore.”\nGabriel García Márquez",
    "“L’unica cosa peggiore della cattiva salute è la cattiva fama.”\nGabriel García Márquez",
    "“Nessun posto nella vita è più triste di un letto vuoto.”\nGabriel García Márquez",
    "“Che strani sono gli uomini, passano la vita a combattere contro i preti e regalano libri di preghiere.”\nGabriel García Márquez",
    "“Non passare il tempo con qualcuno che non sia disposto a passarlo con te.”\nGabriel García Márquez",
    "“Il problema del matrimonio è che finisce tutto di notte dopo aver fatto l'amore, ed è necessario ritornare a ricostruirlo tutte le mattine prima di colazione.”\nGabriel García Márquez",
    "“No, non sono ricco, ma sono un pover'uomo senza soldi, che non è la stessa cosa.”\nGabriel García Márquez",
    "“È impossibile non finire per essere come gli altri credono che uno sia.”\nGabriel García Márquez",
    "“Un bravo scrittore non si riconosce tanto da quello che pubblica quanto da quello che butta nel cestino della carta.”\nGabriel García Márquez",
    "“Si può essere innamorati di diverse persone per volta, e di tutte con lo stesso dolore, senza tradirne nessuna, il cuore ha più stanze di un casinò.”\nGabriel García Márquez",
    "“L’incredulità resiste più della fede, perché si sostenta dei sensi.”\nGabriel García Márquez",
    "“La solitudine è ascoltare il vento e non poterlo raccontare a nessuno.”\nJim Morrison"
];